name: lib_gran_core
description: Biblioteca núcleo
lib_authors:
  - Marcos Souza @devmrcs

version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Firebase
  firebase_storage: 10.1.0
  firebase_core: 1.10.0
  firebase_analytics: 8.3.4
  firebase_crashlytics: 2.3.0
  
  # Network
  dio: 4.0.4
  
  # Network
  connectivity_plus: 2.0.3

  # Storage
  shared_preferences: 2.0.9 

  # Utils 
  equatable: 2.0.3
  flutter_svg: 0.23.0+1
  dartz: 0.10.0
  logging: 1.0.2

  # State Management, DI and Routes
  mobx: 2.0.5
  flutter_mobx: 2.0.2
  flutter_modular: 4.2.0

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: 2.1.5
  mobx_codegen: 2.0.4

  flutter_lints: 1.0.4

  mocktail: 0.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

scripts:
  app_run: flutter run -t lib/main.dart --flavor production

  build_apk: flutter build apk --split-per-abi -t lib/main.dart --flavor production
  build_bundle: flutter build appbundle -t lib/main.dart --flavor production

  mobx: flutter pub run build_runner build
  mobx_delete: flutter pub run build_runner build --delete-conflicting-outputs
  mobx_watch: flutter pub run build_runner watch
  mobx_clean: flutter pub run build_runner clean

  package_outdated: flutter pub outdated
  test_coverage: flutter test --coverage

  adb_restart_tcp: adb tcpip 5555
  adb_connect_tcp: adb connect 192.168.100.45:5555